# Daniel Nicolas Gisolfi
# 2019-8-11
# Reverse Proxy

version: "2"
services: 
   reverse-proxy:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    container_name: reverse-proxy
    volumes:
      # ssl
      # - ${PWD}/ssl:/usr/local/apache2/ssl
      - ${PWD}/sites:/usr/local/apache2/conf/sites
